!!python/object/new:dynamic_reconfigure.encoding.Config
dictitems:
  cob_x_offset_m: 0.0
  cob_y_offset_m: 0.0
  foot_pitch_angle_d_gain: 0.0
  foot_pitch_angle_p_gain: 0.0
  foot_pitch_gyro_d_gain: 0.0
  foot_pitch_gyro_p_gain: 0.0
  foot_pitch_torque_cut_off_frequency: 0.0
  foot_pitch_torque_d_gain: 0.0
  foot_pitch_torque_p_gain: 0.0
  foot_roll_angle_d_gain: 0.0
  foot_roll_angle_p_gain: 0.0
  foot_roll_gyro_d_gain: 0.0
  foot_roll_gyro_p_gain: 0.0
  foot_roll_torque_cut_off_frequency: 0.0
  foot_roll_torque_d_gain: 0.0
  foot_roll_torque_p_gain: 0.0
  foot_x_force_cut_off_frequency: 0.0
  foot_x_force_d_gain: 0.0
  foot_x_force_p_gain: 0.0
  foot_y_force_cut_off_frequency: 0.0
  foot_y_force_d_gain: 0.0
  foot_y_force_p_gain: 0.0
  foot_z_force_cut_off_frequency: 0.0
  foot_z_force_d_gain: 0.0
  foot_z_force_p_gain: 0.0
  groups: !!python/object/new:dynamic_reconfigure.encoding.Config
    dictitems:
      cob_x_offset_m: 0.0
      cob_y_offset_m: 0.0
      foot_pitch_angle_d_gain: 0.0
      foot_pitch_angle_p_gain: 0.0
      foot_pitch_gyro_d_gain: 0.0
      foot_pitch_gyro_p_gain: 0.0
      foot_pitch_torque_cut_off_frequency: 0.0
      foot_pitch_torque_d_gain: 0.0
      foot_pitch_torque_p_gain: 0.0
      foot_roll_angle_d_gain: 0.0
      foot_roll_angle_p_gain: 0.0
      foot_roll_gyro_d_gain: 0.0
      foot_roll_gyro_p_gain: 0.0
      foot_roll_torque_cut_off_frequency: 0.0
      foot_roll_torque_d_gain: 0.0
      foot_roll_torque_p_gain: 0.0
      foot_x_force_cut_off_frequency: 0.0
      foot_x_force_d_gain: 0.0
      foot_x_force_p_gain: 0.0
      foot_y_force_cut_off_frequency: 0.0
      foot_y_force_d_gain: 0.0
      foot_y_force_p_gain: 0.0
      foot_z_force_cut_off_frequency: 0.0
      foot_z_force_d_gain: 0.0
      foot_z_force_p_gain: 0.0
      groups: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      hip_roll_swap_angle_rad: 0.0
      id: 0
      name: Default
      parameters: !!python/object/new:dynamic_reconfigure.encoding.Config
        state: []
      parent: 0
      pitch_angle_cut_off_frequency: 0.0
      pitch_gyro_cut_off_frequency: 0.0
      roll_angle_cut_off_frequency: 0.0
      roll_gyro_cut_off_frequency: 0.0
      state: true
      type: ''
    state: []
  hip_roll_swap_angle_rad: 0.0
  pitch_angle_cut_off_frequency: 0.0
  pitch_gyro_cut_off_frequency: 0.0
  roll_angle_cut_off_frequency: 0.0
  roll_gyro_cut_off_frequency: 0.0
state: []
