r_arm_sh_p1 :   # H54-100-S500-R
   return_delay_time     :  10    # item name : value
   operating_mode        :  3
   shutdown              :  58
   homing_offset         :  0
   torque_limit          :  310
   max_position_limit    :  250950
   min_position_limit    : -250950
   goal_torque           : 310
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 180
   velocity_i_gain       : 452

l_arm_sh_p1 :   # H54-100-S500-R
   return_delay_time     :  10    
   operating_mode        :  3     
   shutdown              :  58    
   homing_offset         :  0     
   torque_limit          :  310
   max_position_limit    :  250950
   min_position_limit    : -250950
   goal_torque           : 310
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 180
   velocity_i_gain       : 452
       
r_arm_sh_r  :   # H54-100-S500-R
   return_delay_time     :  10    
   operating_mode        :  3     
   shutdown              :  58    
   homing_offset         :  0     
   torque_limit          :  310
   max_position_limit    :  250950
   min_position_limit    : -250950
   goal_torque           : 310
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 180
   velocity_i_gain       : 452
       
l_arm_sh_r  :   # H54-100-S500-R
   return_delay_time     :  10    
   operating_mode        :  3     
   shutdown              :  58    
   homing_offset         :  0     
   torque_limit          :  310
   max_position_limit    :  250950
   min_position_limit    : -250950
   goal_torque           : 310
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 180
   velocity_i_gain       : 452
       
r_arm_sh_p2 :   # H54-100-S500-R
   return_delay_time     :  10    
   operating_mode        :  3     
   shutdown              :  58    
   homing_offset         :  0     
   torque_limit          :  310
   max_position_limit    :  250950
   min_position_limit    : -250950
   goal_torque           : 310
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 180
   velocity_i_gain       : 452
       
l_arm_sh_p2 :   # H54-100-S500-R
   return_delay_time     :  10    
   operating_mode        :  3     
   shutdown              :  58    
   homing_offset         :  0     
   torque_limit          :  310
   max_position_limit    :  250950
   min_position_limit    : -250950
   goal_torque           : 310
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 180
   velocity_i_gain       : 452
       
r_arm_el_y  :   # H54-100-S500-R
   return_delay_time     :  10    
   operating_mode        :  3     
   shutdown              :  58    
   homing_offset         :  62738   # 45 deg
   torque_limit          :  310
   max_position_limit    :  250950
   min_position_limit    : -250950
   goal_torque           : 310
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 180
   velocity_i_gain       : 452
       
l_arm_el_y  :   # H54-100-S500-R
   return_delay_time     :  10    
   operating_mode        :  3     
   shutdown              :  58    
   homing_offset         :  -62738  # -45 deg
   torque_limit          :  310
   max_position_limit    :  250950
   min_position_limit    : -250950
   goal_torque           : 310
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 180
   velocity_i_gain       : 452
       
r_arm_wr_r  :   # H42-20-S300-R
   return_delay_time     : 10    
   operating_mode        : 3     
   shutdown              : 58    
   homing_offset         : 0     
   torque_limit          : 372
   max_position_limit    : 151900
   min_position_limit    : -151900
   goal_torque           : 372
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 440
   velocity_i_gain       : 40
       
l_arm_wr_r  :   # H42-20-S300-R
   return_delay_time     : 10    
   operating_mode        : 3     
   shutdown              : 58    
   homing_offset         : 0     
   torque_limit          : 372
   max_position_limit    : 151900
   min_position_limit    : -151900
   goal_torque           : 372
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 440
   velocity_i_gain       : 40
       
r_arm_wr_y  :   # H42-20-S300-R
   return_delay_time     : 10    
   operating_mode        : 3     
   shutdown              : 58    
   homing_offset         : 0     
   torque_limit          : 372
   max_position_limit    : 151900
   min_position_limit    : -151900
   external_port_mod_1   : 0
   external_port_mod_2   : 0
   goal_torque           : 372
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 440
   velocity_i_gain       : 40
       
l_arm_wr_y  :   # H42-20-S300-R
   return_delay_time     : 10    
   operating_mode        : 3     
   shutdown              : 58    
   homing_offset         : 0     
   torque_limit          : 372
   max_position_limit    : 151900
   min_position_limit    : -151900
   external_port_mod_1   : 0
   external_port_mod_2   : 0
   goal_torque           : 372
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 440
   velocity_i_gain       : 40

r_arm_wr_p  :   # H42-20-S300-R
   return_delay_time     : 10    
   operating_mode        : 3     
   shutdown              : 58    
   homing_offset         : 0     
   torque_limit          : 372
   max_position_limit    : 151900
   min_position_limit    : -151900
   external_port_mod_1   : 0
   external_port_mod_2   : 0
   external_port_mod_3   : 0
   external_port_mod_4   : 0
   goal_torque           : 372
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 440
   velocity_i_gain       : 40

l_arm_wr_p  :   # H42-20-S300-R
   return_delay_time     : 10    
   operating_mode        : 3     
   shutdown              : 58    
   homing_offset         : 0     
   torque_limit          : 372
   max_position_limit    : 151900
   min_position_limit    : -151900
   external_port_mod_1   : 0
   external_port_mod_2   : 0
   external_port_mod_3   : 0
   external_port_mod_4   : 0
   goal_torque           : 372
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 440
   velocity_i_gain       : 40

r_leg_hip_y :   # H54-100-S500-R
   return_delay_time     :  10   
   operating_mode        :  3    
   shutdown              :  58   
   homing_offset         :  0    
   torque_limit          :  620
   max_position_limit    :  250950
   min_position_limit    : -250950
   goal_torque           : 620
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 360 # default * 2.0
   velocity_i_gain       : 904 # default * 2.0
       
l_leg_hip_y :   # H54-100-S500-R
   return_delay_time     :  10   
   operating_mode        :  3    
   shutdown              :  58   
   homing_offset         :  0    
   torque_limit          :  620
   max_position_limit    :  250950
   min_position_limit    : -250950
   goal_torque           : 620
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 360 # default * 2.0
   velocity_i_gain       : 904 # default * 2.0
       
r_leg_hip_r :   # H54-200-S500-R
   return_delay_time     :  10    
   operating_mode        :  3     
   shutdown              :  58    
   homing_offset         :  0
   torque_limit          :  1240
   max_position_limit    :  250950
   min_position_limit    : -250950
   goal_torque           : 1240
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 616  # default(308) * 2.0
   velocity_i_gain       : 1546 # default(773) * 2.0
       
l_leg_hip_r :   # H54-200-S500-R
   return_delay_time     :  10    
   operating_mode        :  3     
   shutdown              :  58    
   homing_offset         :  0
   torque_limit          :  1240
   max_position_limit    :  250950
   min_position_limit    : -250950
   goal_torque           : 1240
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 616  # default(308) * 2.0
   velocity_i_gain       : 1546 # default(773) * 2.0
       
r_leg_hip_p :   # H54-200-B500-R
   return_delay_time     :  10    
   operating_mode        :  3     
   shutdown              :  58    
   homing_offset         :  -8365
   torque_limit          :  1240
   max_position_limit    :  250950
   min_position_limit    : -250950
   goal_torque           : 1240
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 616  # default(308) * 2.0
   velocity_i_gain       : 1546 # default(773) * 2.0
       
l_leg_hip_p :   # H54-200-B500-R
   return_delay_time     :  10    
   operating_mode        :  3     
   shutdown              :  58    
   homing_offset         :  0
   torque_limit          :  1240
   max_position_limit    :  250950
   min_position_limit    : -250950
   goal_torque           : 1240
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 616  # default(308) * 2.0
   velocity_i_gain       : 1546 # default(773) * 2.0
       
r_leg_kn_p  :   # H54-200-S500-R
   return_delay_time     :  10    
   operating_mode        :  3     
   shutdown              :  58    
   homing_offset         : -12548    # -9 deg
   torque_limit          :  1240
   max_position_limit    :  250950
   min_position_limit    : -250950
   goal_torque           : 1240
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 770  # default(308) * 2.5
   velocity_i_gain       : 1932 # default(773) * 2.5
       
l_leg_kn_p  :   # H54-200-S500-R
   return_delay_time     :  10    
   operating_mode        :  3     
   shutdown              :  58    
   homing_offset         :  0   #9 deg
   torque_limit          :  1240
   max_position_limit    :  250950
   min_position_limit    : -250950
   goal_torque           : 1240
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 770  # default(308) * 2.5
   velocity_i_gain       : 1932 # default(773) * 2.5
       
r_leg_an_p  :   # H54-200-B500-R
   return_delay_time     :  10    
   operating_mode        :  3     
   shutdown              :  58    
   homing_offset         :  8365  # 6 deg
   torque_limit          :  1240
   max_position_limit    :  250950
   min_position_limit    : -250950
   external_port_mod_1   : 0
   external_port_mod_2   : 0
   goal_torque           : 1240
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 616  # default(308) * 2.0
   velocity_i_gain       : 1546 # default(773) * 2.0
       
l_leg_an_p  :   # H54-200-B500-R
   return_delay_time     :  10    
   operating_mode        :  3     
   shutdown              :  58    
   homing_offset         :  2340   # 6 deg
   torque_limit          :  1240
   max_position_limit    :  4096
   min_position_limit    :  0
   external_port_mod_1   : 0
   external_port_mod_2   : 0
   goal_torque           : 1240
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 616  # default(308) * 2.0
   velocity_i_gain       : 1546 # default(773) * 2.0
       
r_leg_an_r  :   # H54-200-S500-R
   return_delay_time     :  10    
   operating_mode        :  3     
   shutdown              :  58    
   homing_offset         :  0
   torque_limit          :  1240
   max_position_limit    :  250950
   min_position_limit    : -250950
   external_port_mod_1   : 0
   external_port_mod_2   : 0
   external_port_mod_3   : 0
   external_port_mod_4   : 0
   goal_torque           : 1240
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 616  # default(308) * 2.0
   velocity_i_gain       : 1546 # default(773) * 2.0
       
l_leg_an_r  :   # H54-200-S500-R
   return_delay_time     :  10    
   operating_mode        :  3     
   shutdown              :  58    
   homing_offset         :  1843
   torque_limit          :  1240
   max_position_limit    :  4096
   min_position_limit    :  0
   external_port_mod_1   : 0
   external_port_mod_2   : 0
   external_port_mod_3   : 0
   external_port_mod_4   : 0
   goal_torque           : 1240
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 616  # default(308) * 2.0
   velocity_i_gain       : 1546 # default(773) * 2.0
       
torso_y     :   # H54-100-S500-R
   return_delay_time     :  10    
   operating_mode        :  3     
   shutdown              :  58    
   homing_offset         :  0     
   torque_limit          :  310
   max_position_limit    :  250950
   min_position_limit    : -250950
   goal_torque           : 310
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 180
   velocity_i_gain       : 452
       
head_y      :   # H42-20-S300-R
   return_delay_time     : 10    
   operating_mode        : 3     
   shutdown              : 58    
   homing_offset         : 0     
   torque_limit          : 372
   max_position_limit    : 151900
   min_position_limit    : -151900
   goal_torque           : 372
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 440
   velocity_i_gain       : 40
       
head_p      :   # H42-20-S300-R
   return_delay_time     : 10    
   operating_mode        : 3     
   shutdown              : 58    
   homing_offset         : 0     
   torque_limit          : 372
   max_position_limit    : 151900
   min_position_limit    : -151900
   goal_torque           : 372
   goal_velocity         : 0
   goal_acceleration     : 0
   position_p_gain       : 32
   velocity_p_gain       : 440
   velocity_i_gain       : 40
       
r_arm_grip  :   # GRIPPER
   return_delay_time     :   10    
   operating_mode        :    3     
   shutdown              :   48    
   #homing_offset        :    0  there is no homming offset in ctrl table of gripper
   torque_limit          :  250
   max_position_limit    :  750
   min_position_limit    :    0
   goal_torque           :  250
   goal_velocity         :    0
   goal_acceleration     :    0
   position_p_gain       :   64
   velocity_p_gain       :  440
   velocity_i_gain       :   40
       
l_arm_grip  :   # GRIPPER
   return_delay_time     :   10   
   operating_mode        :    3    
   shutdown              :   48   
   #homing_offset        :    0  there is no homming offset in ctrl table of gripper   
   torque_limit          :  250
   max_position_limit    :  750
   min_position_limit    :    0
   goal_torque           :  250
   goal_velocity         :    0
   goal_acceleration     :    0
   position_p_gain       :   64
   velocity_p_gain       :  440
   velocity_i_gain       :   40
       
