right_arm:
# order : joint_name
  1 : r_arm_sh_p1
  2 : r_arm_sh_r
  3 : r_arm_sh_p2
  4 : r_arm_el_y
  5 : r_arm_wr_r
  6 : r_arm_wr_y
  7 : r_arm_wr_p
left_arm:
  1 : l_arm_sh_p1
  2 : l_arm_sh_r
  3 : l_arm_sh_p2
  4 : l_arm_el_y
  5 : l_arm_wr_r
  6 : l_arm_wr_y
  7 : l_arm_wr_p
legs:
  1 : r_leg_hip_y
  2 : l_leg_hip_y
  3 : r_leg_hip_r
  4 : l_leg_hip_r
  5 : r_leg_hip_p
  6 : l_leg_hip_p
  7 : r_leg_kn_p
  8 : l_leg_kn_p
  9 : r_leg_an_p
  10 : l_leg_an_p
  11 : r_leg_an_r
  12 : l_leg_an_r
body: 
  1 : torso_y
  2 : head_y
  3 : head_p